# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ADCHEM UBC
description: >- # this means to ignore newlines until "baseurl:"
  Data Analysis Workshop
baseurl: "/adchem" # the subpath of your site, e.g. /blog
url: "https://www.daisubc.github.io/adchem" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
highlighter: rouge
collections:
  members:
    output: true
    permalink: /members/:path/
    
exclude: [vendor]
include: ["_pages"]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
